baseURL = "/"
languageCode = "en-us"
title = "IBDGC"
theme = "academic"
summaryLength = "30"



[params]
	description = "ICBDG site description goes here"

[[menu.main]]
  name = "DATA"
  url = "/data"
  weight = 100

[[menu.main]]
  name = "ABOUT"
  url = "/about"
  weight = 200

[[menu.main]]
  name = "NEWS"
  url = "/news"
  weight = 300

[[menu.main]]
  name = "RESEARCH"
  url = "/research"
  weight =400

[[menu.main]]
  name = "PATIENTS"
  url = "/patients"
  weight = 500


 [[menu.footer]]
  name = "DATA"
  url = "/data"
  weight = 100

[[menu.footer]]
  name = "ABOUT"
  url = "/about"
  weight = 200

[[menu.footer]]
  name = "NEWS"
  url = "/news"
  weight = 300

[[menu.footer]]
  name = "RESEARCH"
  url = "/research"
  weight = 400

[[menu.footer]]
  name = "PATIENTS"
  url = "/patients"
  weight = 500 
