# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#   name = "DATA"
#   url = "/data"
#   weight = 100

[[main]]
  name = "ABOUT"
  url = ""
  weight = 200
  identifier = "about-menu"

[[main]]
  name = "Overview"
  url = "/about"
  weight = 10
  parent = "about-menu"

[[main]]
  name = "Genetic Research Centers"
  url = "/grc"
  weight = 30
  parent = "about-menu"

[[main]]
  name = "Data Coordinating Center"
  url = "/dcc"
  weight = 40
  parent = "about-menu"

[[main]]
  name = "NEWS"
  url = "/news"
  weight = 300

[[main]]
  name = "RESEARCH"
  url = ""
  weight =400
  identifier = "research-menu"

[[main]]
  name = "Projects"
  url = "/research"
  weight = 10
  parent = "research-menu"

[[main]]
  name = "Publications"
  url = "/publication"
  weight = 20
  parent = "research-menu"

[[main]]
  name = "Webinar Series"
  url = "/talk"
  weight = 30
  parent = "research-menu"

#[[main]]
#  name = "Data"
#  url = "/data"
#  weight = 40
#  parent = "research-menu"

[[main]]
  name = "PATIENTS"
  url = "/patients"
  weight = 500

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
