variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  image:
    name: klakegg/hugo:0.88.1-ext-alpine-ci
    entrypoint : ['']
  before_script:
    - git submodule update --init --recursive
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - production

deploy:
  stage: deploy
  image:
    name: banst/awscli
    entrypoint: [""]
  script:
    - aws configure set region us-east-1
    - aws s3 cp public s3://$S3_BUCKET 
