name: Build and Deploy

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build site
        uses: docker://klakegg/hugo:0.88.1-ext-alpine-ci
        run: hugo
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Upload to S3
        if: success()
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
          source_dir: public/
          bucket_url: s3://${{ secrets.S3_BUCKET }}

