name: site build and deploy

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    container: klakegg/hugo@0.88.1-ext-alpine-ci

    steps:
    - uses: actions/checkout@v1

    - run: git submodule update --init --recursive

    - run: hugo

