name: Build and Deploy

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build site
        run: |
          docker run --rm -v ${{ github.workspace }}:/src klakegg/hugo:0.88.1-ext-alpine-ci hugo --minify --destination public
  deploy:
    runs-on: ubuntu-latest
      - name: Upload to S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Sync to S3
        uses: aws-actions/aws-cli@v1
        with:
          args: s3 sync public s3://${{ variables.S3_BUCKET }} --delete

